### ISSUE TITLE
3d ödeme sayfası boş geliyor ? 

### ISSUE THREAD

**Issue by trixmaxzero** [mstfsnc/nestpay#2]
3d Ödeme sayfasına yönlendirdiğinde sayfa boş açılıyor 
![image](https://user-images.githubusercontent.com/11073291/37532767-03151992-2951-11e8-9cb3-a08f17bd267d.png)

![image](https://user-images.githubusercontent.com/11073291/37532788-11bf3b58-2951-11e8-9496-27fd1bae972b.png)

**Comment by mstfsnc** [comment]
Gateway de bir sorun vardı sanırım, requesti hatalı yaptığında bile hatayla birlikte geriye dönüş yapması gerekiyordu.

**Comment by huseyinoymak** [comment]
işlem linki güncel olmayabilir
https://spos.isbank.com.tr/servlet/est3Dgate
https://spos.isbank.com.tr/fim/est3Dgate
olarak değiştirilmeli sanırım

**Comment by mstfsnc** [comment]
Dökümanlara göre doğru gatewayi kullanıyor aslında.

**Comment by mstfsnc** [comment]
Bu sorunda bir aktivite olmadığı için kapatıyorum
