### ISSUE TITLE
taksit tablosu için geçersiz değer

### ISSUE THREAD

**Issue by savasturkoglu1** [mstfsnc/nestpay#4]
"Taksit tablosu için geçersiz değer" diye bir hata aldık, bir de yabancı para birimleri için  " bu para birimine taksit yapılamaz"  şeklinde hata alıyoruz. çözümü nedir acaba

**Comment by mstfsnc** [comment]
Para birimi kullanmadan önce banka ile iletişime geçip bildirmeniz gerekiyor yanlış hatırlamıyorsam. Daha önce usd satış yapabilmek için böyle bir tanımlatma yapmıştık.

Taksit hatasını hangi bankayla işlem yaparken almıştın?

**Comment by savasturkoglu1** [comment]
AbstractPayment.php de ki `if ($installment = $this->getInstallment()) {
            $data['taksit'] = $installment;
        }` blouğunu kaldırınca o hatayı vermedi ama tabi müşterinin bankasıyla görüşmesi gerekti yinede :)

**Comment by mstfsnc** [comment]
O bloğu kaldırdığında taksit yapamazsın. `installment` değerine ne set etmiştin? Bir de önceden üye işyerleri taksitli alışveriş yapmadan önce bankayla görüşüp oranları belirliyor ve taksit sayılarını tanımlatıyordu, hala öyle mi bilmiyorum.

**Comment by mstfsnc** [comment]
Bu sorunda bir aktivite olmadığı için kapatıyorum
